### ISSUE TITLE
Other export format

### ISSUE THREAD

**Issue by KikeVen** [ai-autocoder/vscode-todo#2]
I installed the extension and like it overall. Initially, I expected to be able to export TODO lists as Markdown files. I currently use Markdown to track tasks because it allows me to add checkboxes and easily convert the list to a PDF for clients. I hoped to streamline this process by creating and exporting TODO lists directly in Markdown format within the extension. 

I didn't see any option to save as Markdown, could it be added?

**Example of what I already do in Markdown editor:**

> It can be done in your extension already, I just need to export it as Markdown

# Project name

Project description here

## Project category 1

Stuff I like to write to impress my clients

* [ ] Task 1
* [x] Task 2
* [ ] Task 3
* [x] Task 4

```python
print("hello world")  # must edit
```

## Project category 2

More stuff I like to write to impress my clients

* [x] Task 1
* [x] Task 2
* [ ] Task 3
* [ ] Task 4

thank you

**Comment by ai-autocoder** [comment]
Hello, this is an interesting feature and should be fairly simple to add.
This is my implementation idea:
Create a markdown file for each list (User, Workspace) depending on the export selection.
Note elements can be appended to the file as they are, while todo elements will be converted to the markdown syntax: * [ ] Task.
For files list I`m not quite sure if it can be useful to export the entire list in one markdown file, in that case there should be a header indicating the name of the associated file. It may be more worth to export a list attached to a single specific file.
What are your thoughts?

**Comment by KikeVen** [comment]
I agree with you about making it available for 'user' and 'Workspace'. This would quickly alleviate the redundancy of having to copy-paste from your extension to an external markdown file. One could download whatever they made in the 'user' or 'workspace' and edit it outside of the extension.

If it isn't more complicated adding the file name to the 'file' list for export would help. Again. A user can export all files and in VS Code with the Markdown extension users can edit the exports.

* In the future, you could have Markdown import too. If we worked on something outside of the extension in Markdown, we could import it, continue checking off tasks, add more, edit other parts of the notes, and then export it again.

* Other future features could include dragging tasks between lists (User, Workspace, and File)

Thank you for asking and again for the extension.

~e
